//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailMVCWebEF.Models.ML
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderTbl()
        {
            this.ProductOrderDetails = new HashSet<ProductOrderDetail>();
        }
    
        public int id { get; set; }
        public System.DateTime creationTime { get; set; }
        public bool isActive { get; set; }
        public double total { get; set; }
        public bool isPaid { get; set; }
        public Nullable<int> FK_id_idTable { get; set; }
        public Nullable<int> FK_id_idRestaurant { get; set; }
    
        public virtual TableTbl TableTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrderDetail> ProductOrderDetails { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
