//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailMVCWebEF.Models.ML
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrderDetail
    {
        public int id { get; set; }
        public int quantity { get; set; }
        public Nullable<int> FK_id_idProduct { get; set; }
        public Nullable<int> FK_id_idOrders { get; set; }
    
        public virtual OrderTbl OrderTbl { get; set; }
        public virtual Product Product { get; set; }
    }
}
