//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailMVCWebEF.Models.ML
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductOrderDetails = new HashSet<ProductOrderDetail>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool isActive { get; set; }
        public string description { get; set; }
        public string allergens { get; set; }
        public string nutritionFacts { get; set; }
        public float price { get; set; }
        public string imageUrl { get; set; }
        public string code { get; set; }
        public Nullable<int> FK_id_idRestaurant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrderDetail> ProductOrderDetails { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
