//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailMVCWebEF.Models.ML
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableTbl()
        {
            this.Books = new HashSet<Book>();
            this.OrderTbls = new HashSet<OrderTbl>();
        }
    
        public int id { get; set; }
        public bool isAvailable { get; set; }
        public int code { get; set; }
        public int capacity { get; set; }
        public Nullable<int> FK_id_idRestaurant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Books { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTbl> OrderTbls { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
